#!/usr/bin/env python3
"""Geneva Motor Haus — build about.html.

THE WORDS AND THE PHOTOGRAPHS are the client's own /about page
(genevamotorhaus.com/about, rendered 2026-09-14): its sections in its
order — mission, values, story, why us, the visit — and its four
photographs, uncaptioned, because nothing says which cars they are.

TRIMMED, NOT EXTENDED. The page is template-shaped, and the homepage's
ledger already refused its figures (12+ years, 5000+ sold, 98%) and its
superlatives. The same line is held here, and the promises nobody has
confirmed — no hidden fees, history reports, thorough inspection, decades of
experience — are left out. Every sentence used is recorded against its
source in docs/content-ledger-about.json.

THE LANGUAGE is the finale page's: eyebrow plates, Zilla Slab, the bone
chapter, raised cards on hairlines.

    python3 tools/build-about.py
"""
import html
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from gmh_chrome import ROOT, chrome  # noqa: E402

OUT = ROOT / "about.html"
LEDGER = ROOT / "docs/content-ledger-about.json"
IMG = "assets/img/about"
DIRECTIONS = "https://www.google.com/maps/dir/?api=1&amp;destination=600+Faust+Rd+Unit+8%2C+Burlington%2C+WI+53105"
ARROW = ('<svg class="btn__arrow" width="13" height="13" viewBox="0 0 13 13" fill="none" aria-hidden="true">'
         '<path d="M2 6.5h9M7.4 3 11 6.5 7.4 10" stroke="currentColor" stroke-width="1.3"/></svg>')
e = html.escape

top, footer = chrome(current=("about.html", "About"))

MISSION = [
    "Our mission goes beyond simply selling vehicles. We connect our clients with luxury and performance automobiles through a personalized, transparent process — because buying a vehicle should be an exciting and memorable journey, crafted with care, attention to detail and a genuine passion for the art of motoring.",
    "Each vehicle in our inventory is hand-selected for its quality and condition, from collector cars to modern performance icons.",
    "We take pride in building long-term relationships founded on trust and integrity. Whether you’re searching for your next car or expanding a collection, we’re here to help at every stage.",
]
VALUES = [
    ("Excellence", "We hold every vehicle we offer, and every interaction we have, to our standards."),
    ("Integrity", "Transparency and honesty are at the core of everything we do."),
    ("Passion", "Our love for luxury vehicles drives us to provide an exceptional experience for every customer."),
    ("Service", "We go above and beyond for our customers before, during and after the sale."),
]
STORY = [
    "Geneva Motor Haus was founded with a simple yet powerful vision: to create a destination where automotive enthusiasts and luxury vehicle seekers could find exceptional vehicles matched with unparalleled service. What started as a passion project is now a showroom in Burlington, Wisconsin.",
    "We have built our reputation by carefully selecting each vehicle in our inventory and treating every customer relationship as a long-term partnership — whether you’re looking for a daily driver or a collector’s dream.",
]
WHY = [
    ("Curated selection", "Every vehicle in our inventory is hand-selected.", ("See the inventory", "srp.html")),
    ("A smooth deal", "From initial inquiry to final delivery, we guide you through every step — and handle the paperwork, financing options and logistics.", ("Explore financing", "finance.html")),
    ("Nationwide transportation", "Half our cars leave Wisconsin, and transportation is available nationwide.", ("Shipping", "index_finale_v2.html#shipping")),
    ("Convenient location", "Located in Burlington, Wisconsin, we’re easily accessible and offer a comfortable showroom experience.", ("Get directions", DIRECTIONS)),
]

mission_p = "\n".join(f'        <p class="rv-item" style="--rv-i: {k}">{e(p)}</p>' for k, p in enumerate(MISSION))
story_p = "\n".join(f'        <p class="rv-item" style="--rv-i: {k}">{e(p)}</p>' for k, p in enumerate(STORY))
values_li = "\n".join(f'        <li class="ab-values__item"><h3 class="ab-values__t">{t}</h3><p class="ab-values__p">{e(p)}</p></li>' for t, p in VALUES)
REL = ' rel="noopener"'
why_li = "\n".join(
    f'        <li class="ab-why__item"><p class="ab-why__k">{t}</p><p class="ab-why__v">{e(p)}</p>'
    f'<a class="ab-why__link" href="{href}"{REL if href.startswith("http") else ""}>{label} {ARROW}</a></li>'
    for t, p, (label, href) in WHY)

page = f"""<!doctype html>
<!-- ============================================================
     GENEVA MOTOR HAUS — about
     ============================================================
     GENERATED by tools/build-about.py. The words and photographs are the
     client's own /about page (rendered 2026-09-14), trimmed of the template
     claims nobody has confirmed — docs/content-ledger-about.json.
     ============================================================ -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>About — Geneva Motor Haus · Burlington, WI</title>
<meta name="description" content="Geneva Motor Haus in Burlington, Wisconsin: from low-mile collectibles to everyday transportation, each vehicle hand-selected.">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Zilla+Slab:wght@500;600;700&display=swap" rel="stylesheet">

<link rel="icon" href="assets/logos/gmh-icon-64.png" type="image/png">
<link rel="apple-touch-icon" href="assets/logos/gmh-icon-180.png">

<link rel="stylesheet" href="assets/css/tokens.css?v=4">
<link rel="stylesheet" href="assets/css/main.css?v=3">
<link rel="stylesheet" href="assets/css/v2.css?v=3">
<link rel="stylesheet" href="assets/css/v3.css?v=3">
<link rel="stylesheet" href="assets/css/geneva-final-v2.css?v=21">
<link rel="stylesheet" href="assets/css/about-v2.css?v=1">
</head>
<body class="v2 is-v3 is-gmh is-about">

{top}<main>
  <!-- 1 — THE HEAD, and the lot at sunset -->
  <section class="ab-head" data-reveal aria-labelledby="ab-title">
    <div class="shell">
      <p class="micro gmh-plate rv-eyebrow">About us</p>
      <h1 class="ab-head__title" id="ab-title"><span class="ttl-line">Where passion</span> <span class="ttl-line">meets perfection.</span></h1>
      <p class="ab-head__lede rv-lede">From low-mile collectibles to everyday transportation. Each vehicle in our inventory is hand-selected in Burlington, Wisconsin.</p>
      <div class="ab-head__acts rv-act">
        <a class="btn btn--accent" href="srp.html">Browse inventory {ARROW}</a>
        <a class="btn btn--line" href="tel:+12622496777">Call (262) 249-6777 {ARROW}</a>
      </div>
    </div>
  </section>

  <div class="shell ab-hero">
    <figure class="ab-hero__frame rv-self rv-photo" data-reveal>
      <img src="{IMG}/about-hero.jpg" srcset="{IMG}/about-hero-sm.jpg 1000w, {IMG}/about-hero.jpg 2000w" sizes="100vw"
           alt="A yellow Porsche 911 in a parking lot at sunset" width="2000" height="1400" fetchpriority="high" decoding="async">
    </figure>
  </div>

  <!-- 2 — MISSION -->
  <section data-reveal class="ab-sec ab-mission" aria-labelledby="ab-mission-title">
    <div class="shell ab-split">
      <figure class="ab-photo rv-photo">
        <img src="{IMG}/about-mission.jpg" srcset="{IMG}/about-mission-sm.jpg 1000w, {IMG}/about-mission.jpg 2000w" sizes="(max-width: 960px) 100vw, 45vw"
             alt="Two men standing beside a white Porsche 911" width="2000" height="1333" loading="lazy" decoding="async">
      </figure>
      <div class="ab-copy">
        <p class="micro gmh-plate rv-eyebrow">Our mission</p>
        <h2 class="ab-sec__title" id="ab-mission-title"><span class="ttl-line">Excellence in every detail.</span></h2>
{mission_p}
      </div>
    </div>
  </section>

  <!-- 3 — VALUES -->
  <section data-reveal class="ab-sec ab-values" aria-labelledby="ab-values-title">
    <div class="shell">
      <p class="micro gmh-plate rv-eyebrow">Our values</p>
      <h2 class="ab-sec__title" id="ab-values-title"><span class="ttl-line">What drives us.</span></h2>
      <ul class="ab-values__list rv-stagger" style="--rv-from: 1.6">
{values_li}
      </ul>
    </div>
  </section>

  <!-- 4 — STORY: the bone chapter, and a buyer's own sentence -->
  <section data-reveal class="ab-sec ab-story" aria-labelledby="ab-story-title">
    <div class="shell ab-split ab-split--flip">
      <div class="ab-copy">
        <p class="micro gmh-plate rv-eyebrow">Our story</p>
        <h2 class="ab-sec__title" id="ab-story-title"><span class="ttl-line">Built on excellence.</span></h2>
{story_p}
        <blockquote class="ab-quote rv-item" style="--rv-i: 2"><p>“He has very nice vehicles and he stands behind them.”</p><cite>Patrick</cite></blockquote>
      </div>
      <figure class="ab-photo rv-photo">
        <img src="{IMG}/about-story.jpg" srcset="{IMG}/about-story-sm.jpg 1000w, {IMG}/about-story.jpg 2000w" sizes="(max-width: 960px) 100vw, 45vw"
             alt="A white Porsche 911 on a desert road below snow-capped mountains" width="2000" height="1400" loading="lazy" decoding="async">
      </figure>
    </div>
  </section>

  <!-- 5 — WHY US: each reason with its way in -->
  <section data-reveal class="ab-sec ab-why" aria-labelledby="ab-why-title">
    <div class="shell">
      <p class="micro gmh-plate rv-eyebrow">Why buy from us</p>
      <h2 class="ab-sec__title" id="ab-why-title"><span class="ttl-line">The Geneva Motor Haus difference.</span></h2>
      <ul class="ab-why__grid rv-stagger" style="--rv-from: 1.6">
{why_li}
      </ul>
    </div>
  </section>

  <!-- 6 — THE VISIT -->
  <section class="ab-visit" data-reveal aria-labelledby="ab-visit-title">
    <div class="shell">
      <div class="ab-visit__card rv-photo">
        <figure class="ab-visit__media">
          <img src="{IMG}/about-visit.jpg" alt="A pink Porsche 718 Cayman GT4 parked in front of a white-columned house" width="1024" height="683" loading="lazy" decoding="async">
        </figure>
        <div class="ab-visit__copy">
          <h2 class="ab-visit__title" id="ab-visit-title"><span class="ttl-line">Ready to experience</span> <span class="ttl-line">excellence?</span></h2>
          <p class="ab-visit__p rv-lede">Visit our showroom or browse our inventory online.</p>
          <dl class="ab-visit__facts rv-item" style="--rv-i: 0">
            <div><dt>Showroom</dt><dd>600 Faust Rd, Unit 8<br>Burlington, WI 53105</dd></div>
            <div><dt>Hours</dt><dd>Monday – Friday 10AM – 4PM<br>Saturday by appointment · Sunday closed</dd></div>
          </dl>
          <div class="ab-visit__acts rv-act">
            <a class="btn btn--accent" href="srp.html">Browse inventory {ARROW}</a>
            <a class="btn btn--line" href="{DIRECTIONS}" rel="noopener">Get directions {ARROW}</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

{footer}


<script src="assets/js/main-final-v2.js?v=2" defer></script>
<script src="assets/js/geneva-final-v2.js?v=2" defer></script>
</body>
</html>
"""
OUT.write_text(page)

SRC = "genevamotorhaus.com/about, rendered 2026-09-14"
ledger = {
    "project": "geneva-motor-haus", "page": "about.html", "compiled": "2026-09-14",
    "note": f"Words and photographs from {SRC}. Trimmed, never extended; the homepage ledger's refusals (docs/content-ledger.json notUsed) hold here too.",
    "entries": [
        {"id": "ab-tagline", "claim": "Where passion meets perfection.", "status": "verified", "source": f"{SRC}: hero 'Where Passion Meets Perfection'", "sourceType": "live-site", "appearsAt": ["#ab-title"]},
        {"id": "ab-lede", "claim": "From low-mile collectibles to everyday transportation. Each vehicle in our inventory is hand-selected in Burlington, Wisconsin.", "status": "verified", "source": "homepage ledger 'hand-selected' (/about: 'Each vehicle in our inventory is hand-selected') and the live site's hero line; location from the contact section", "sourceType": "live-site", "appearsAt": [".ab-head__lede"]},
        {"id": "ab-mission", "claim": " / ".join(MISSION), "status": "verified", "source": f"{SRC}, 'Our Mission', trimmed: removed 'unlike any other', 'world’s most exceptional', 'exotic' (contradicted by stock), 'provenance', 'meticulously inspected, detailed, and maintained to meet the highest standards', 'rare', 'industry professionals'", "sourceType": "live-site", "appearsAt": [".ab-mission"]},
        {"id": "ab-values", "claim": " / ".join(f"{t}: {p}" for t, p in VALUES), "status": "verified", "source": f"{SRC}, 'Our Values', trimmed: 'the highest standards' → 'our standards'; 'No hidden fees, no surprises.' removed; 'to ensure complete customer satisfaction' shortened", "sourceType": "live-site", "appearsAt": [".ab-values"]},
        {"id": "ab-story", "claim": " / ".join(STORY), "status": "verified", "source": f"{SRC}, 'Our Story', trimmed: 'has grown into one of the region's most trusted luxury automotive dealerships' → 'is now a showroom in Burlington, Wisconsin' (the published address); 'rigorous quality standards', 'decades of combined experience', 'you'll find exactly what you're seeking' removed", "sourceType": "live-site", "appearsAt": [".ab-story"]},
        {"id": "ab-quote", "claim": "“He has very nice vehicles and he stands behind them.” — Patrick", "status": "verified", "source": "customer review on genevamotorhaus.com, as used on the homepage (reputation-stand-behind)", "sourceType": "live-site", "appearsAt": [".ab-quote"]},
        {"id": "ab-why-selection", "claim": WHY[0][1], "status": "verified", "source": f"{SRC}, 'Curated Selection', trimmed of 'thoroughly inspected to ensure it meets our exacting standards'", "sourceType": "live-site", "appearsAt": [".ab-why__item"]},
        {"id": "ab-why-process", "claim": WHY[1][1], "status": "verified", "source": "homepage ledger process-copy (Process tab, corroborated by reviews)", "sourceType": "live-site", "appearsAt": [".ab-why__item"]},
        {"id": "ab-why-shipping", "claim": WHY[2][1], "status": "verified", "source": "homepage/VDP ledger vdp-shipping (AAN ticket: half the cars go out of state; transportation available)", "sourceType": "client-data", "appearsAt": [".ab-why__item"]},
        {"id": "ab-why-location", "claim": WHY[3][1], "status": "verified", "source": f"{SRC}, 'Convenient Location', verbatim (homepage ledger about-location)", "sourceType": "live-site", "appearsAt": [".ab-why__item"]},
        {"id": "ab-visit", "claim": "Ready to experience excellence? Visit our showroom or browse our inventory online.", "status": "verified", "source": f"{SRC}, call to action, trimmed of 'We're ready to help you find the perfect luxury vehicle'", "sourceType": "live-site", "appearsAt": [".ab-visit"]},
        {"id": "ab-address-hours", "claim": "600 Faust Rd, Unit 8, Burlington, WI 53105 · Monday – Friday 10AM – 4PM · Saturday by appointment · Sunday closed", "status": "verified", "source": "homepage ledger contact-address, hours", "sourceType": "live-site", "appearsAt": [".ab-visit__facts"]},
        {"id": "ab-phone", "claim": "(262) 249-6777", "status": "verified", "source": "homepage ledger contact-phone", "sourceType": "live-site", "appearsAt": [".ab-head__acts"]},
        {"id": "ab-photos", "claim": "Four photographs, uncaptioned: yellow 911 at sunset; two men with a white 911; white 911 below mountains; 718 Cayman GT4 before a columned house", "status": "verified", "source": f"{SRC}: the page's own four images (assets/img/source/about/), resized. No car is named as stock and no person is named.", "sourceType": "live-site", "appearsAt": [".ab-hero__frame", ".ab-photo", ".ab-visit__media"]},
    ],
    "notUsed": [
        {"claim": "12+ Years Experience · 5000+ Vehicles Sold · 98% Customer Satisfaction", "reason": "refused on the homepage already: unverified, implausible against the stock and the sold list (82); ask the client"},
        {"claim": "one of the region's most trusted luxury automotive dealerships · premier destination · unmatched · unlike any other · the world’s most exceptional · the finest", "reason": "superlatives without a source (CP6)"},
        {"claim": "No hidden fees · complete vehicle history reports · honest pricing", "reason": "business promises not confirmed by the client (CP6)"},
        {"claim": "meticulously inspected, detailed, and maintained · thoroughly inspected", "reason": "a service promise not confirmed by the client (CP6)"},
        {"claim": "decades of combined experience · years of specialized expertise", "reason": "an unverified duration (CP5/CP6)"},
        {"claim": "exotic automobiles", "reason": "contradicted by the stock on the day of capture (homepage ledger)"},
    ],
}
LEDGER.write_text(json.dumps(ledger, indent=2, ensure_ascii=False))
print(f"wrote {OUT.name} ({OUT.stat().st_size // 1024} KB); ledger {len(ledger['entries'])} entries, {len(ledger['notUsed'])} not used")
