#!/usr/bin/env python3
"""Geneva Motor Haus — build sold.html from assets/data/sold-2026-09-14.json.

The SRP again (same measures, same filters bar, same card from
tools/gmh_cards.py), for the dealer's sold list: every card carries the SOLD
tag, and none is a link — the live site has no page for a sold car.

Only fields the sold cards carry are filtered on: make, year, mileage. A
price is on 9 of 82 cards, so there is no price filter or sort (CP7).

    python3 tools/build-sold.py
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from gmh_cards import ARROW, card, e  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "assets/data/sold-2026-09-14.json"
HOME = ROOT / "index_finale_v2.html"
OUT = ROOT / "sold.html"
LEDGER = ROOT / "docs/content-ledger-sold.json"
LIVE_INVENTORY = "https://www.genevamotorhaus.com/inventory"

inv = json.loads(DATA.read_text())
V = inv["vehicles"]
home = HOME.read_text()

GLASS = ('<svg width="16" height="16" viewBox="0 0 17 17" fill="none" aria-hidden="true">'
         '<circle cx="7.2" cy="7.2" r="5.4" stroke="currentColor" stroke-width="1.4"/>'
         '<path d="m11.4 11.4 3.8 3.8" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg>')


def between(text, start, end, include_end=True):
    a = text.index(start)
    b = text.index(end, a) + (len(end) if include_end else 0)
    return text[a:b]


chrome_top = between(home, '<span class="scroll-sentinel"', "<main>", include_end=False).replace(LIVE_INVENTORY, "srp.html")
chrome_top = re.sub(r'<a href="sold\.html">Sold</a>', '<a href="sold.html" aria-current="page">Sold</a>', chrome_top)
footer = between(home, "<footer", "</footer>").replace(LIVE_INVENTORY, "srp.html")

WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven",
         "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]


def in_words(n):
    if n < 20:
        return WORDS[n]
    t, u = divmod(n, 10)
    return TENS[t] + ("-" + WORDS[u] if u else "")


YEAR_BANDS = [("2020 and newer", 2020, 9999), ("2010 – 2019", 2010, 2019), ("2000 – 2009", 2000, 2009), ("Before 2000", 0, 1999)]
MILES_BANDS = [("Under 30,000 mi", 1, 29999), ("30,000 – 60,000 mi", 30000, 59999), ("60,000 – 100,000 mi", 60000, 99999), ("100,000 mi and over", 100000, 999999)]


def opt(name, value, label, n):
    return (f'            <label class="srp-opt"><input type="checkbox" name="{name}" value="{e(str(value))}">'
            f'<span class="srp-opt__name">{e(label)}</span><span class="srp-opt__n">{n}</span></label>')


def band_options(name, bands, field):
    rows = []
    for label, lo, hi in bands:
        n = sum(1 for v in V if v.get(field) is not None and lo <= v[field] <= hi)
        if n:
            rows.append(opt(name, f"{lo}-{hi}", label, n))
    return "\n".join(rows)


makes = {}
for v in V:
    makes[v["make"]] = makes.get(v["make"], 0) + 1
makes = sorted(makes.items(), key=lambda kv: (-kv[1], kv[0]))
make_opts = "\n".join(opt("make", m, m, n) for m, n in makes)
make_tiles = "\n".join(
    f'        <li><button class="srp-make" type="button" data-make="{e(m)}" aria-pressed="false">{e(m)}<span>{n}</span></button></li>'
    for m, n in makes[:10])


def facet(fid, title, options):
    return f"""          <details class="srp-facet" id="{fid}">
            <summary class="srp-facet__trigger">{title}<span class="srp-facet__n" hidden></span></summary>
            <div class="srp-facet__panel">
              <fieldset class="srp-opts"><legend class="u-visually-hidden">{title}</legend>
{options}
              </fieldset>
              <button class="srp-facet__clear" type="button">Clear</button>
            </div>
          </details>"""


cards = "\n".join(card(v, index=i, sold=True) for i, v in enumerate(V))
count = len(V)

page = f"""<!doctype html>
<!-- ============================================================
     GENEVA MOTOR HAUS — sold vehicles
     ============================================================
     GENERATED by tools/build-sold.py from assets/data/sold-2026-09-14.json.

     The SRP again — same measures (CMC's, 2026-09-14), same filters bar,
     same card — for the dealer's sold list. Every card carries SOLD and none
     is a link: the live site has no page for a sold car.

     THE DATA is genevamotorhaus.com/sold rendered on 14 Sep 2026
     (docs/source/site-live-sold-2026-09-14.json; ledger
     docs/content-ledger-sold.json). Filters are only the fields every card
     carries — make, year, mileage; a price is on 9 of 82 cards, so there is
     no price filter or sort (CP7). Mileage listed as 0, or as one impossible
     figure, is not shown.
     ============================================================ -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sold — Geneva Motor Haus · Burlington, WI</title>
<meta name="description" content="Cars recently sold by Geneva Motor Haus in Burlington, Wisconsin.">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Zilla+Slab:wght@500;600;700&display=swap" rel="stylesheet">

<link rel="icon" href="assets/logos/gmh-icon-64.png" type="image/png">
<link rel="apple-touch-icon" href="assets/logos/gmh-icon-180.png">

<link rel="stylesheet" href="assets/css/tokens.css?v=4">
<link rel="stylesheet" href="assets/css/main.css?v=3">
<link rel="stylesheet" href="assets/css/v2.css?v=3">
<link rel="stylesheet" href="assets/css/v3.css?v=3">
<link rel="stylesheet" href="assets/css/geneva-final-v2.css?v=21">
<link rel="stylesheet" href="assets/css/srp-v2.css?v=9">
</head>
<body class="v2 is-v3 is-gmh is-srp is-soldpage">

{chrome_top}<main>
  <section class="srp-head" data-reveal aria-labelledby="srp-title">
    <div class="shell">
      <p class="micro srp-head__eyebrow rv-eyebrow">Sold</p>
      <h1 class="srp-head__title" id="srp-title"><span class="ttl-line">{in_words(count).capitalize()} cars,</span> <span class="ttl-line">sold from Burlington.</span></h1>
      <div class="srp-makes-wrap">
        <p class="srp-makes__title rv-lede" id="srp-makes-title">Most sold makes</p>
        <ul class="srp-makes rv-stagger" style="--rv-from: 3" aria-labelledby="srp-makes-title">
{make_tiles}
        </ul>
      </div>
    </div>
  </section>

  <section class="srp-tools" id="srp-tools" data-reveal aria-label="Refine results">
    <div class="shell">
      <div class="srp-tools__box rv-lede">
        <p class="micro srp-tools__eyebrow">Search the sold list</p>
        <div class="srp-tools__row">
          <button class="srp-filters-open" type="button" aria-expanded="false" aria-controls="srp-facets">Filters <span class="srp-filters-open__n" hidden></span></button>
          <div class="srp-facets" id="srp-facets">
            <div class="srp-sheet__head">
              <p class="srp-sheet__title">Filters</p>
              <button class="srp-sheet__close" type="button" aria-label="Close filters"><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m1 1 12 12M13 1 1 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></button>
            </div>
{facet("f-make", "Make", make_opts)}
{facet("f-year", "Year", band_options("year", YEAR_BANDS, "year"))}
{facet("f-miles", "Mileage", band_options("miles", MILES_BANDS, "mileage"))}
            <div class="srp-sheet__foot">
              <button class="srp-sheet__reset" type="button">Reset</button>
              <button class="btn btn--accent srp-sheet__show" type="button">Show <b data-srp-count>{count}</b> cars</button>
            </div>
          </div>
          <form class="srp-search" role="search" action="sold.html" method="get">
            <label class="u-visually-hidden" for="srp-q">Search year, make or model</label>
            {GLASS}
            <input id="srp-q" name="q" type="search" placeholder="Search year, make, model" autocomplete="off">
          </form>
          <p class="srp-count" aria-live="polite"><b data-srp-count>{count}</b> of {count} <span class="srp-dated">· as listed 14&#160;Sep&#160;2026</span></p>
          <label class="srp-sort"><span>Sort:</span>
            <select id="srp-sort" name="sort">
              <option value="listed">Most recent</option>
              <option value="year-desc">Year newest first</option>
              <option value="year-asc">Year oldest first</option>
              <option value="miles-asc">Mileage low to high</option>
            </select>
          </label>
        </div>
        <div class="srp-chips" id="srp-chips" hidden>
          <ul class="srp-chips__row" aria-label="Active filters"></ul>
          <button class="srp-chips__clear" type="button">Clear all</button>
        </div>
      </div>
    </div>
  </section>

  <section class="srp-results" aria-label="Sold vehicles">
    <div class="shell">
      <ul class="srp-grid" id="srp-grid">
{cards}
      </ul>
      <div class="srp-empty" id="srp-empty" hidden>
        <p class="srp-empty__t">No sold cars match these filters.</p>
        <button class="btn btn--line srp-empty__clear" type="button">Clear filters {ARROW}</button>
      </div>
      <p class="srp-onward"><a class="btn btn--line" href="srp.html">See the cars in stock {ARROW}</a></p>
    </div>
  </section>
</main>

{footer}


<script src="assets/js/main-final-v2.js?v=2" defer></script>
<script src="assets/js/geneva-final-v2.js?v=2" defer></script>
<script src="assets/js/srp-v2.js?v=3" defer></script>
</body>
</html>
"""
OUT.write_text(page)

ledger = {"project": "geneva-motor-haus", "page": "sold.html", "compiled": "2026-09-14",
          "note": "Every figure on sold.html is the dealer's own sold list, rendered 2026-09-14 (docs/source/site-live-sold-2026-09-14.json).",
          "entries": [{"id": "sold-count", "claim": f"{count} cars sold", "status": "dated-requires-reconciliation", "captureDate": "2026-09-14",
                       "source": "genevamotorhaus.com/sold: 'Showing 82 vehicles', rendered 2026-09-14", "sourceType": "live-site", "appearsAt": [".srp-head__title", ".srp-count"]}],
          "notUsed": [{"claim": v["titleAsListed"] + f" — mileage as listed {v['mileageAsListed']:,}", "reason": "0 or an impossible figure; not shown"} for v in V if v["mileage"] is None and v["mileageAsListed"] is not None]}
for v in V:
    parts = [f"{v['year']} {v['make']} {v['model']} — sold"]
    if v.get("mileage"):
        parts.append(f"{v['mileage']:,} miles")
    if v.get("price"):
        parts.append(f"${v['price']:,}")
    ledger["entries"].append({"id": f"sold-{v['slug']}", "claim": " — ".join(parts), "status": "dated-requires-reconciliation", "captureDate": "2026-09-14",
                              "source": f"genevamotorhaus.com/sold card '{v['titleAsListed']}', rendered 2026-09-14", "sourceType": "live-site",
                              "appearsAt": [f".srp-card[data-slug='{v['slug']}']"]})
LEDGER.write_text(json.dumps(ledger, indent=2, ensure_ascii=False))
print(f"wrote {OUT.name}: {count} sold cars, {len(makes)} makes, {OUT.stat().st_size // 1024} KB; ledger {len(ledger['entries'])} entries")
