#!/usr/bin/env python3
"""Geneva Motor Haus — build contact.html.

THE FORM is the All Auto Network contact form
(aanmaster2027.aandemo.com/contact-us/, formname=contacts, read 2026-09-14):
fname, lname, email, phone, contact_mode (morning / afternoon / evening),
message, i_agree — its names, its required set and its consent sentence.
It has no conditional parts. AAN shows names as placeholders; here every
field has a real label.

THE WORDS AND FACTS are Geneva's own /contact (rendered 2026-09-14): the
three ways to reach them, the hours, the holiday note, the social profiles
and the map embed. Trimmed of what nobody has confirmed ("as soon as
possible", "all your automotive needs") — docs/content-ledger-contact.json.
The live page's hero photograph is an aerial of Geneva, Switzerland, not the
Burlington showroom, and is not used.

The form layer is finance.html's (assets/css/finance-v2.css,
assets/js/finance-v2.js); contact-v2.css adds the head, the time pills and
the location card. The map is the homepage's own section.

    python3 tools/build-contact.py
"""
import html
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from gmh_chrome import ROOT, chrome  # noqa: E402

OUT = ROOT / "contact.html"
LEDGER = ROOT / "docs/content-ledger-contact.json"
e = html.escape
ARROW = ('<svg class="btn__arrow" width="13" height="13" viewBox="0 0 13 13" fill="none" aria-hidden="true">'
         '<path d="M2 6.5h9M7.4 3 11 6.5 7.4 10" stroke="currentColor" stroke-width="1.3"/></svg>')
DIRECTIONS = "https://www.google.com/maps/dir/?api=1&amp;destination=600+Faust+Rd+Unit+8%2C+Burlington%2C+WI+53105"
MAP_SRC = ("https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2934.332791834392!2d-88.26140192387547!3d42.65430267116704"
           "!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88058462663f005d%3A0xa5edfc0e4d09552a"
           "!2s600%20Faust%20Rd%20%238%2C%20Burlington%2C%20WI%2053105%2C%20USA!5e0!3m2!1sen!2s!4v1763210872893!5m2!1sen!2s&amp;t=m")
SOCIAL = [
    ("Instagram", "https://www.instagram.com/genevamotorhaus/"),
    ("YouTube", "https://www.youtube.com/@GenevaMotorHaus"),
    ("TikTok", "https://www.tiktok.com/@geneva.motor.haus"),
    ("Facebook", "https://www.facebook.com/profile.php?id=61583395092139"),
]

top, footer = chrome(current=("contact.html", "Contact"))


def field(name, label, span=2, kind="text", req=False, attrs=""):
    star = '<span class="fin-req" aria-hidden="true">*</span>' if req else ""
    r = " required" if req else ""
    fid = f"f-{name}"
    if kind == "textarea":
        control = f'<textarea id="{fid}" name="{name}" rows="6"{r}{attrs}></textarea>'
    else:
        control = f'<input id="{fid}" name="{name}" type="{kind}"{r}{attrs}>'
    return f'<div class="fin-field f-{span}"><label for="{fid}">{e(label)}{star}</label>{control}</div>'


when = ('<fieldset class="ct-when"><legend>Best time to contact<span class="fin-req" aria-hidden="true">*</span></legend><div class="ct-when__opts">'
        + "".join(f'<label><input type="radio" name="contact_mode" value="{v}" required><span>{t}</span></label>'
                  for v, t in (("morning", "Morning"), ("afternoon", "Afternoon"), ("evening", "Evening")))
        + "</div></fieldset>")

form = ('<fieldset class="fin-sec rv-self" id="ct-form-sec" data-reveal><legend class="fin-sec__head"><span class="fin-sec__t">Your message</span></legend>'
        '<div class="fin-grid">'
        + field("fname", "First name", 3, req=True, attrs=' autocomplete="given-name"')
        + field("lname", "Last name", 3, req=True, attrs=' autocomplete="family-name"')
        + field("email", "Email", 3, "email", True, attrs=' autocomplete="email"')
        + field("phone", "Phone", 3, "tel", True, attrs=' autocomplete="tel"')
        + "</div>" + when
        + '<div class="fin-grid ct-grid-msg">' + field("message", "Message", 6, "textarea", attrs=' placeholder="Tell us how we can help"') + "</div>"
        + '<label class="fin-check fin-check--agree"><input type="checkbox" name="i_agree" value="1" id="f-i_agree" required>'
          '<span>Please note that by completing this form, you agree to being contacted via text, phone and email.'
          '<span class="fin-req" aria-hidden="true">*</span></span></label>'
        + "</fieldset>")

social_li = "".join(f'<li><a href="{u}" rel="noopener">{n}</a></li>' for n, u in SOCIAL)

page = f"""<!doctype html>
<!-- ============================================================
     GENEVA MOTOR HAUS — contact
     ============================================================
     GENERATED by tools/build-contact.py. The form is AAN's contact form
     (contacts: names, required set, consent) in Geneva's language; the
     facts are Geneva's /contact, trimmed (docs/content-ledger-contact.json).
     A static preview cannot send a message, and says so when the form is
     submitted.
     ============================================================ -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Contact — Geneva Motor Haus · Burlington, WI</title>
<meta name="description" content="Contact Geneva Motor Haus: (262) 249-6777, Info@GenevaMotorHaus.com, 600 Faust Rd, Unit 8, Burlington, WI 53105.">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Zilla+Slab:wght@500;600;700&display=swap" rel="stylesheet">

<link rel="icon" href="assets/logos/gmh-icon-64.png" type="image/png">
<link rel="apple-touch-icon" href="assets/logos/gmh-icon-180.png">

<link rel="stylesheet" href="assets/css/tokens.css?v=4">
<link rel="stylesheet" href="assets/css/main.css?v=3">
<link rel="stylesheet" href="assets/css/v2.css?v=3">
<link rel="stylesheet" href="assets/css/v3.css?v=3">
<link rel="stylesheet" href="assets/css/geneva-final-v2.css?v=21">
<link rel="stylesheet" href="assets/css/finance-v2.css?v=4">
<link rel="stylesheet" href="assets/css/contact-v2.css?v=2">
</head>
<body class="v2 is-v3 is-gmh is-fin is-contact">

{top}<main>
  <!-- 1 — THE HEAD: the three ways in, each one tap away -->
  <section class="ct-head" data-reveal aria-labelledby="ct-title">
    <div class="shell ct-head__inner">
      <div class="ct-head__copy">
        <p class="micro gmh-plate rv-eyebrow">Contact us</p>
        <h1 class="ct-head__title" id="ct-title"><span class="ttl-line">Get in touch.</span></h1>
        <p class="ct-head__lede rv-lede">Whether you prefer to call, email or visit us in person, we’re here to help.</p>
        <div class="ct-head__acts rv-act">
          <a class="btn btn--accent" href="#apply">Send a message {ARROW}</a>
          <a class="btn btn--line" href="tel:+12622496777">Call (262) 249-6777 {ARROW}</a>
        </div>
      </div>
      <ul class="ct-ways rv-stagger" style="--rv-from: 1.6" aria-label="Ways to reach us">
        <li class="ct-way"><p class="ct-way__k">Phone</p><a class="ct-way__v" href="tel:+12622496777">(262) 249-6777</a><p class="ct-way__p">Call us during business hours.</p></li>
        <li class="ct-way"><p class="ct-way__k">Email</p><a class="ct-way__v" href="mailto:Info@GenevaMotorHaus.com">Info@GenevaMotorHaus.com</a><p class="ct-way__p">Send us an email anytime.</p></li>
        <li class="ct-way"><p class="ct-way__k">Showroom</p><a class="ct-way__v" href="{DIRECTIONS}" rel="noopener">600 Faust Rd, Unit 8, Burlington, WI 53105</a><p class="ct-way__p">Visit our showroom. Saturdays by appointment.</p></li>
      </ul>
    </div>
  </section>

  <!-- 2 — THE FORM, with where and when beside it -->
  <section class="fin-apply" id="apply" aria-labelledby="ct-form-title">
    <div class="shell">
      <div class="fin-apply__head" data-reveal>
        <p class="micro gmh-plate rv-eyebrow">Contact form</p>
        <h2 class="fin-apply__title" id="ct-form-title"><span class="ttl-line">Send us a message.</span></h2>
        <p class="fin-apply__lede rv-lede">Fill out the form and we’ll get back to you. For immediate assistance, call us at <a class="ct-inline" href="tel:+12622496777">(262) 249-6777</a>. Fields marked <span class="fin-req">*</span> are required.</p>
      </div>
      <div class="fin-apply__body">
        <div class="fin-apply__main">
          <form class="fin-form" id="fin-form" novalidate>
{form}
            <div class="fin-actions">
              <button class="btn btn--accent" type="submit">Send message {ARROW}</button>
            </div>
          </form>
          <div class="fin-sent" id="fin-sent" hidden tabindex="-1">
            <p class="fin-sent__t">Thanks<span data-sent-name></span>.</p>
            <p class="fin-sent__p">This preview doesn’t send messages. To reach Geneva Motor Haus now, call <a href="tel:+12622496777">(262) 249-6777</a>.</p>
          </div>
        </div>
        <aside class="ct-card rv-self" data-reveal aria-label="Location and hours">
          <div class="ct-card__sec">
            <p class="ct-card__t">Geneva Motor Haus</p>
            <p class="ct-card__addr">600 Faust Rd, Unit 8<br>Burlington, WI 53105</p>
            <a class="ct-card__link" href="{DIRECTIONS}" rel="noopener">Get directions {ARROW}</a>
          </div>
          <div class="ct-card__sec">
            <p class="ct-card__k">Business hours</p>
            <dl class="ct-hours">
              <div><dt>Monday – Friday</dt><dd>10AM – 4PM</dd></div>
              <div><dt>Saturday</dt><dd>By appointment</dd></div>
              <div><dt>Sunday</dt><dd>Closed</dd></div>
            </dl>
            <p class="ct-card__note">We’re closed on major holidays. Please call ahead to confirm hours during holiday seasons.</p>
          </div>
          <div class="ct-card__sec">
            <p class="ct-card__k">Follow us</p>
            <ul class="ct-social">{social_li}</ul>
          </div>
        </aside>
      </div>
    </div>
  </section>

  <!-- 3 — THE MAP, edge to edge: the homepage's own section -->
  <section class="gf-map ct-map rv-self" data-reveal aria-label="Map — 600 Faust Rd, Unit 8, Burlington, WI 53105">
    <iframe class="gf-map__frame" title="Map of 600 Faust Rd, Unit 8, Burlington, WI 53105" loading="lazy" referrerpolicy="no-referrer-when-downgrade"
            src="{MAP_SRC}"></iframe>
  </section>
</main>

{footer}


<script src="assets/js/main-final-v2.js?v=2" defer></script>
<script src="assets/js/geneva-final-v2.js?v=2" defer></script>
<script src="assets/js/finance-v2.js?v=5" defer></script>
</body>
</html>
"""
OUT.write_text(page)

G = "genevamotorhaus.com/contact, rendered 2026-09-14"
ledger = {
    "project": "geneva-motor-haus", "page": "contact.html", "compiled": "2026-09-14",
    "note": "The form is AAN's contact form (aanmaster2027.aandemo.com/contact-us/, formname=contacts, read 2026-09-14). The facts and words are Geneva's /contact, trimmed.",
    "entries": [
        {"id": "ct-heading", "claim": "Get in touch.", "status": "verified", "source": f"{G}: hero 'Get In Touch'", "sourceType": "live-site", "appearsAt": ["#ct-title"]},
        {"id": "ct-lede", "claim": "Whether you prefer to call, email or visit us in person, we’re here to help.", "status": "verified", "source": f"{G}, 'Multiple Ways to Connect', trimmed of 'with all your automotive needs. Our team is ready to help you find the perfect vehicle.'", "sourceType": "live-site", "appearsAt": [".ct-head__lede"]},
        {"id": "ct-phone", "claim": "(262) 249-6777 — Call us during business hours.", "status": "verified", "source": f"{G}, Phone card; homepage ledger contact-phone", "sourceType": "live-site", "appearsAt": [".ct-way", ".ct-head__acts", ".fin-apply__lede", ".fin-sent__p"]},
        {"id": "ct-email", "claim": "Info@GenevaMotorHaus.com — Send us an email anytime.", "status": "verified", "source": f"{G}, Email card; homepage ledger contact-email", "sourceType": "live-site", "appearsAt": [".ct-way"]},
        {"id": "ct-address", "claim": "600 Faust Rd, Unit 8, Burlington, WI 53105 — Visit our showroom. Saturdays by appointment.", "status": "verified", "source": f"{G}, Address card ('Visit our showroom') and hours ('Saturday Appt Only'); homepage ledger contact-address", "sourceType": "live-site", "appearsAt": [".ct-way", ".ct-card"]},
        {"id": "ct-hours", "claim": "Monday – Friday 10AM – 4PM · Saturday by appointment · Sunday closed", "status": "verified", "source": f"{G}, 'Business Hours'; homepage ledger hours", "sourceType": "live-site", "appearsAt": [".ct-hours"]},
        {"id": "ct-holidays", "claim": "We’re closed on major holidays. Please call ahead to confirm hours during holiday seasons.", "status": "verified", "source": f"{G}, verbatim (also docs/source/site-copy-2026-09-10.json)", "sourceType": "live-site", "appearsAt": [".ct-card__note"]},
        {"id": "ct-form-intro", "claim": "Fill out the form and we’ll get back to you. For immediate assistance, call us at (262) 249-6777.", "status": "verified", "source": f"{G}, 'Contact Form' intro, 'as soon as possible' removed", "sourceType": "live-site", "appearsAt": [".fin-apply__lede"]},
        {"id": "ct-form", "claim": "Form fields (fname, lname, email, phone, contact_mode, message, i_agree) and the consent sentence", "status": "verified", "source": "AAN contacts form config, GET /api/?module=form&formname=contacts&action=get_config, 2026-09-14", "sourceType": "client-data", "appearsAt": ["#fin-form"]},
        {"id": "ct-social", "claim": " · ".join(f"{n} {u}" for n, u in SOCIAL), "status": "verified", "source": f"{G}, footer profile links (the page's own social tiles link to '#')", "sourceType": "live-site", "appearsAt": [".ct-social"]},
        {"id": "ct-map", "claim": "Google Maps embed of 600 Faust Rd #8, Burlington, WI", "status": "verified", "source": f"{G} and the homepage's map section: the same embed URL", "sourceType": "live-site", "appearsAt": [".ct-map"]},
    ],
    "notUsed": [
        {"claim": "Hero photograph: aerial of Geneva, Switzerland (uploads/media/6917438463681_1763132292.jpg)", "reason": "not the Burlington showroom; on a contact page it misleads about where the business is (CP7)"},
        {"claim": "We're Here to Help You Find Your Dream Vehicle · all your automotive needs · the perfect vehicle", "reason": "template superlatives (CP6)"},
        {"claim": "we'll get back to you as soon as possible · We will get back to you shortly", "reason": "an unconfirmed response-time promise (CP6)"},
        {"claim": "Stay updated with our latest inventory, special offers, and automotive news", "reason": "'special offers' is unconfirmed; the links stand on their own"},
        {"claim": "Geneva's own short form (name, email, phone, subject, message)", "reason": "the AAN contacts form is the spec"},
    ],
}
LEDGER.write_text(json.dumps(ledger, indent=2, ensure_ascii=False))
print(f"wrote {OUT.name} ({OUT.stat().st_size // 1024} KB); ledger {len(ledger['entries'])} entries")
